version: '3'
services:
  elasticsearch:
    image:  elasticsearch:latest
    container_name: elasticsearch
    restart: always
    networks:
      - elk
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
       - ./elasticsearch/data:/usr/share/elasticsearch/data

  logstash:
    image: logstash:latest
    container_name: logstash
    restart: always
    networks:
       - elk
    ports:
      - "9601:9601"
    volumes:
      - ./logstash/config-dir:/config-dir
    command: logstash -f /config-dir
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:latest
    container_name: kibana
    restart: always
    networks:
       - elk
    ports:
       - "5601:5601"
    depends_on:
       - elasticsearch


  zipkin:
    image: zipkin:latest
    container_name: zipkin
    restart: always
    networks:
      - elk
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=elasticsearch
    depends_on:
       - elasticsearch

networks:
    elk: