server:
  port: 8771

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: cloud-config
#  profiles:
#    active: subversion #使用SVN作为配置中心时使用
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true
      server:
        git:
          uri: https://github.com/yungby/cloud_properties_master
          searchPaths: '{application}'
          label: master
#        svn:
#          uri: svn://localhost/demo/spring_cloud/parent/trunk/properties/
#          username: luoming
#          password: L_ming_svn
#          search-paths: '{application}'
#          default-label: trunk

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

info:
  version:
#debug: true
